# Generated by Django 5.2.11 on 2026-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_used_trial_user_trial_end_user_trial_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_credits',
            field=models.IntegerField(default=2, help_text='Free quiz attempts remaining'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_quizzes_taken',
            field=models.IntegerField(default=0, help_text='Total quizzes taken (analytics)'),
        ),
    ]
