# Generated by Django 5.2.11 on 2026-02-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_quiz_credits_user_total_quizzes_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_quizzes_used',
            field=models.IntegerField(default=0, help_text='Number of free quizzes used (0-4)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quiz_credits',
            field=models.IntegerField(default=4, help_text='Free quiz attempts remaining'),
        ),
    ]
