# Generated by Django 5.2.11 on 2026-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_free_quizzes_used_alter_user_quiz_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, default='', help_text='Parent email for receipts & progress reports', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, default='', help_text='Parent phone in 2547XXXXXXXX format', max_length=15),
        ),
    ]
