# Generated by Django 5.2 on 2026-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_allow_null_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='free_quizzes_used',
            field=models.IntegerField(default=0, help_text='Number of free quizzes used'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quiz_credits',
            field=models.IntegerField(default=2, help_text='Free quiz attempts remaining'),
        ),
    ]
