# Generated by Django 5.2.11 on 2026-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_free_quizzes_used_alter_user_quiz_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, default='', help_text='School the student attends (optional, self-reported)', max_length=150),
        ),
    ]
