# Generated by Django 5.2.11 on 2026-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_previews_used',
            field=models.JSONField(blank=True, default=list, help_text='Strands previewed free in the AI Tutor / Flash Cards'),
        ),
    ]
