# Generated by Django 6.0.2 on 2026-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='detailed_feedback',
            field=models.JSONField(blank=True, help_text='Question-by-question AI feedback', null=True),
        ),
    ]
