# Generated by Django 6.0.2 on 2026-02-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_attempt_detailed_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marking_scheme',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_marks',
            field=models.IntegerField(default=1),
        ),
    ]
