# Generated by Django 5.2.11 on 2026-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_attempt_id_alter_classquizassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='total_marks_awarded',
            field=models.FloatField(default=0, help_text='Actual marks earned'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_max_marks',
            field=models.FloatField(default=0, help_text='Maximum marks possible'),
        ),
    ]
