# Generated by Django 5.2.11 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_attempt_total_marks_awarded_attempt_total_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('topical', 'Topical Quiz'), ('exam', 'Exam')], default='topical', help_text='Type of assessment', max_length=20),
        ),
    ]
