# Generated by Django 5.2.11 on 2026-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='set_number',
            field=models.IntegerField(blank=True, help_text='Set number for exams (e.g., 1, 2, 3...)', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='term',
            field=models.IntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], help_text='Term for exams (null for topical quizzes)', null=True),
        ),
    ]
