# Generated by Django 5.2.11 on 2026-02-17 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_quiz_set_number_quiz_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_kes', models.IntegerField(help_text='Price in Kenyan Shillings')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Termly (3 months)'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('duration_days', models.IntegerField(help_text='How many days this plan lasts')),
                ('max_quizzes_per_day', models.IntegerField(default=5, help_text='0 = unlimited')),
                ('can_access_b2c', models.BooleanField(default=True)),
                ('can_access_analytics', models.BooleanField(default=False)),
                ('can_download_pdf', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['order', 'price_kes'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(help_text='M-Pesa transaction code e.g. QGH7X9K2PL', max_length=20, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number used for payment e.g. 0712345678', max_length=15)),
                ('amount_paid', models.IntegerField(help_text='Amount student claims to have paid (KES)')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified — Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='questions.subscriptionplan')),
            ],
            options={
                'db_table': 'payment_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.paymentrequest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AIGradingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('strictness_level', models.IntegerField(default=5, help_text='1=Very Lenient, 10=Very Strict', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('allow_spelling_errors', models.BooleanField(default=True, help_text='Accept minor spelling mistakes')),
                ('max_spelling_errors', models.IntegerField(default=2, help_text='Max spelling errors to still award marks')),
                ('require_perfect_grammar', models.BooleanField(default=False, help_text='Require grammatically correct answers')),
                ('award_partial_marks', models.BooleanField(default=True, help_text='Give partial credit for partially correct answers')),
                ('partial_marks_threshold', models.FloatField(default=0.5, help_text='Minimum correctness to award partial marks (0.5 = 50%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('penalize_duplicate_points', models.BooleanField(default=True, help_text="Don't award marks for repeated/duplicate points")),
                ('accept_synonyms', models.BooleanField(default=True, help_text='Accept synonyms and alternative phrasings')),
                ('feedback_tone', models.CharField(choices=[('encouraging', 'Encouraging'), ('neutral', 'Neutral'), ('professional', 'Professional')], default='encouraging', help_text='Tone of AI feedback', max_length=20)),
                ('provide_study_tips', models.BooleanField(default=True, help_text='Include study tips in feedback')),
                ('flag_for_manual_review_below', models.FloatField(default=0.4, help_text='Flag for manual review if confidence < this (0.4 = 40%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('auto_approve_above', models.FloatField(default=0.9, help_text='Auto-approve if confidence > this (0.9 = 90%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Leave blank for global settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
            ],
            options={
                'db_table': 'ai_grading_settings',
                'ordering': ['subject', 'grade'],
                'unique_together': {('subject', 'grade')},
            },
        ),
    ]
