# Generated by Django 5.2.11 on 2026-02-20 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_subscriptionplan_paymentrequest_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigradingsettings',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='aigradingsettings',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='allow_spelling_errors',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='award_partial_marks',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='strictness_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=20)),
                ('join_code', models.CharField(max_length=10, unique=True)),
                ('time_per_question', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=80)),
                ('term', models.CharField(max_length=20)),
                ('week', models.PositiveSmallIntegerField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(max_length=40)),
                ('learner_level', models.CharField(max_length=60)),
                ('prior_knowledge', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('is_practical', models.BooleanField(default=False)),
                ('practical_area', models.CharField(blank=True, max_length=200)),
                ('generated_plan', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('truefalse', 'True/False'), ('open', 'Open-Ended')], default='mcq', max_length=12)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_index', models.IntegerField(blank=True, null=True)),
                ('points', models.PositiveSmallIntegerField(default=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.classroom')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='questions.classroom')),
            ],
            options={
                'unique_together': {('classroom', 'student_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('selected_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.studentsession')),
            ],
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='accept_synonyms',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='auto_approve_above',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='feedback_tone',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='flag_for_manual_review_below',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='max_spelling_errors',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='partial_marks_threshold',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='penalize_duplicate_points',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='provide_study_tips',
        ),
        migrations.RemoveField(
            model_name='aigradingsettings',
            name='require_perfect_grammar',
        ),
    ]
