# Generated by Django 5.2.11 on 2026-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_aigradingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aigradingsettings',
            table=None,
        ),
    ]
