# Generated by Django 5.2.11 on 2026-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_aigradingsettings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional diagram, graph, or illustration', null=True, upload_to='question_images/'),
        ),
    ]
