# Generated by Django 5.2.11 on 2026-02-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.livequestion'),
        ),
    ]
