# Generated by Django 5.2.11 on 2026-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_studentanswer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonplan',
            old_name='topic',
            new_name='strand',
        ),
        migrations.RenameField(
            model_name='lessonplan',
            old_name='subtopic',
            new_name='substrand',
        ),
    ]
