# Generated by Django 5.2.11 on 2026-03-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_rename_topic_lessonplan_strand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
