# Generated by Django 5.2.11 on 2026-03-07 11:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_guestusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional diagram, graph, or illustration', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='question_images/'),
        ),
    ]
