# Generated by Django 5.2.11 on 2026-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_paymentrequest_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='worked_solution',
            field=models.JSONField(blank=True, default=None, help_text='Step-by-step solution with LaTeX', null=True),
        ),
    ]
