# Generated by Django 5.2.11 on 2026-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_question_worked_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='mpesa_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
