# Generated by Django 5.2.11 on 2026-03-21 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_paymentrequest_mpesa_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The full passage, poem or excerpt')),
                ('passage_type', models.CharField(choices=[('prose', 'Prose'), ('poem', 'Poem'), ('dialogue', 'Dialogue'), ('excerpt', 'Excerpt'), ('article', 'Article')], default='prose', max_length=20)),
                ('grade', models.IntegerField()),
                ('author', models.CharField(blank=True, help_text='Author or source', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='questions.subject')),
            ],
            options={
                'db_table': 'passages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, help_text='Link to reading passage if this is a comprehension question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.passage'),
        ),
    ]
