# Generated by Django 5.2.11 on 2026-03-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_passage_question_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_label', models.CharField(help_text='e.g. a, b, c, i, ii, iii', max_length=10)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('structured', 'Structured Answer'), ('essay', 'Essay'), ('math', 'Mathematical Expression'), ('fill_blank', 'Fill in the Blank')], default='structured', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.TextField(blank=True)),
                ('max_marks', models.IntegerField(default=1)),
                ('marking_scheme', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='questions.question')),
            ],
            options={
                'db_table': 'question_parts',
                'ordering': ['order', 'part_label'],
            },
        ),
    ]
