# Generated by Django 5.2.11 on 2026-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_questionpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='passage_type',
            field=models.CharField(choices=[('prose', 'Prose'), ('poem', 'Poem'), ('dialogue', 'Dialogue'), ('excerpt', 'Excerpt'), ('article', 'Article'), ('cloze', 'Broken Passage / Cloze')], default='prose', max_length=20),
        ),
    ]
