# Generated by Django 5.2.11 on 2026-04-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_passage_passage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('termly', 'Termly (3 months)'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
