# Generated by Django 5.2.11 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_add_weekly_billing_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('quote', 'Quote'), ('story', 'Story'), ('tip', 'Tip')], default='quote', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('exam', 'Exam Motivation'), ('study', 'Study Tips'), ('life', 'Life Skills'), ('success', 'Success Stories')], default='general', max_length=20)),
                ('text', models.TextField(help_text='The quote, story, or tip text')),
                ('author', models.CharField(blank=True, help_text='Who said/wrote it (optional)', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('grade_min', models.IntegerField(default=4, help_text='Minimum grade to show this to')),
                ('grade_max', models.IntegerField(default=12, help_text='Maximum grade to show this to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivational Content',
                'verbose_name_plural': 'Motivational Content',
                'db_table': 'motivational_content',
                'ordering': ['-created_at'],
            },
        ),
    ]
