# Generated by Django 5.2 on 2026-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_motivationalcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestusage',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
