# Generated by Django 5.2.11 on 2026-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_add_session_id_to_guestusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='ai_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
