# Generated by Django 5.2 on 2026-04-16 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_add_ai_report_to_studentsession'),
        ('users', '0008_allow_null_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=20)),
                ('join_code', models.CharField(max_length=10, unique=True)),
                ('time_per_question', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'live_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'student'], name='attempt_quiz_student_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', '-started_at'], name='attempt_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['status', '-started_at'], name='attempt_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'status'], name='attempt_quiz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['-started_at'], name='attempt_started_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', '-created_at'], name='q_topic_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by', '-created_at'], name='q_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='q_type_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='q_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='q_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['subject', 'is_active'], name='quiz_subj_active_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by', '-created_at'], name='quiz_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['grade', 'is_active'], name='quiz_grade_active_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', '-created_at'], name='quiz_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_type'], name='quiz_type_idx'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livequestion',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.livesession'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='questions.livesession'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
