# Generated by Django 5.2 on 2026-04-17 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_livesession_remove_classroom_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigradingsettings',
            options={'ordering': ['subject', 'grade']},
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='accept_synonyms',
            field=models.BooleanField(default=True, help_text='Accept synonyms and alternative phrasings'),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='auto_approve_above',
            field=models.FloatField(default=0.9, help_text='Auto-approve if confidence > this (0.9 = 90%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='feedback_tone',
            field=models.CharField(choices=[('encouraging', 'Encouraging'), ('neutral', 'Neutral'), ('professional', 'Professional')], default='encouraging', help_text='Tone of AI feedback', max_length=20),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='flag_for_manual_review_below',
            field=models.FloatField(default=0.4, help_text='Flag for manual review if confidence < this (0.4 = 40%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='max_spelling_errors',
            field=models.IntegerField(default=2, help_text='Max spelling errors to still award marks'),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='partial_marks_threshold',
            field=models.FloatField(default=0.5, help_text='Minimum correctness to award partial marks (0.5 = 50%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='penalize_duplicate_points',
            field=models.BooleanField(default=True, help_text="Don't award marks for repeated/duplicate points"),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='provide_study_tips',
            field=models.BooleanField(default=True, help_text='Include study tips in feedback'),
        ),
        migrations.AddField(
            model_name='aigradingsettings',
            name='require_perfect_grammar',
            field=models.BooleanField(default=False, help_text='Require grammatically correct answers'),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='allow_spelling_errors',
            field=models.BooleanField(default=True, help_text='Accept minor spelling mistakes'),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='award_partial_marks',
            field=models.BooleanField(default=True, help_text='Give partial credit for partially correct answers'),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='strictness_level',
            field=models.IntegerField(default=5, help_text='1=Very Lenient, 10=Very Strict', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='aigradingsettings',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='aigradingsettings',
            unique_together={('subject', 'grade')},
        ),
        migrations.AlterModelTable(
            name='aigradingsettings',
            table='ai_grading_settings',
        ),
    ]
