# Generated by Django 5.2 on 2026-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_alter_aigradingsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cached_ai_explanation',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI explanation for MCQ — avoids repeat API calls', null=True),
        ),
    ]
