# Generated by Django 5.2.11 on 2026-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_add_cached_ai_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalcontent',
            name='preview',
            field=models.CharField(blank=True, help_text='Short teaser shown on the card', max_length=300),
        ),
        migrations.AddField(
            model_name='motivationalcontent',
            name='title',
            field=models.CharField(blank=True, help_text="Card title, e.g. 'Anger Management'", max_length=200),
        ),
        migrations.AlterField(
            model_name='motivationalcontent',
            name='text',
            field=models.TextField(help_text='The full content shown when user clicks the card'),
        ),
    ]
