# Generated by Django 5.2.11 on 2026-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_add_title_preview_to_motivational_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='table_data',
            field=models.JSONField(blank=True, help_text='Table structure for table question type', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('math', 'Mathematical Expression'), ('structured', 'Structured Answer'), ('essay', 'Essay'), ('table', 'Table')], default='mcq', max_length=20),
        ),
    ]
