# Generated by Django 5.2.11 on 2026-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_add_table_data_to_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('math', 'Mathematical Expression'), ('structured', 'Structured Answer'), ('essay', 'Essay'), ('table', 'Table'), ('multipart', 'Multipart')], default='mcq', max_length=20),
        ),
    ]
