# Generated by Django 5.2.11 on 2026-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_add_multipart_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('grading', 'Grading'), ('completed', 'Completed'), ('grading_failed', 'Grading Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
    ]
