# Generated by Django 5.2.11 on 2026-05-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_add_option_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='statement_subtype',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('trading_account', 'Trading / P&L Account'), ('cash_flow', 'Cash Flow Statement'), ('t_account', 'T-Account / Ledger'), ('trial_balance', 'Trial Balance')], default='', help_text='For financial_statement type: balance_sheet | income_statement | trading_account | cash_flow | t_account | trial_balance', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('math', 'Mathematical Expression'), ('structured', 'Structured Answer'), ('essay', 'Essay'), ('table', 'Table'), ('multipart', 'Multipart'), ('financial_statement', 'Financial Statement')], default='mcq', max_length=20),
        ),
    ]
