# Generated by Django 5.2.11 on 2026-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_add_financial_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='statement_subtype',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='questionpart',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('structured', 'Structured Answer'), ('essay', 'Essay'), ('math', 'Mathematical Expression'), ('fill_blank', 'Fill in the Blank'), ('table', 'Table'), ('financial_statement', 'Financial Statement')], default='structured', max_length=20),
        ),
    ]
