# Generated by Django 5.2.11 on 2026-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_add_statement_subtype_table_data_to_questionpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cached_ai_lesson',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI-generated lesson for the tutor — avoids repeat API calls', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='free_quizzes_remaining',
            field=models.IntegerField(default=5),
        ),
    ]
