# Generated by Django 5.2.11 on 2026-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_topic_cached_ai_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrand',
            name='cached_ai_lesson',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI lesson focused on this sub-strand', null=True),
        ),
        migrations.AddField(
            model_name='substrand',
            name='cached_flashcards',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI flashcard deck for this sub-strand', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='cached_flashcards',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI flashcard deck for the WHOLE strand (fallback when no substrands)', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cached_ai_lesson',
            field=models.JSONField(blank=True, default=None, help_text='Cached AI lesson for the WHOLE strand (fallback when no substrands)', null=True),
        ),
    ]
