# Generated by Django 5.2.11 on 2026-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_substrand_cached_ai_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='cached_ai_explanation',
            field=models.JSONField(blank=True, default=None, help_text="Cached AI-rephrased version of this part's explanation", null=True),
        ),
    ]
