# Generated by Django 5.2.11 on 2026-07-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_questionpart_cached_ai_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='marks_overridden',
            field=models.BooleanField(default=False, help_text="A human corrected the AI's marks on this attempt"),
        ),
        migrations.AddField(
            model_name='attempt',
            name='override_note',
            field=models.TextField(blank=True, default='', help_text='Why the marks were overridden (audit trail)'),
        ),
    ]
